name: Build and Attach Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r win-x64
      env:
        Configuration: Release

    - name: Compress build output
      run: |
        powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\output\* -DestinationPath $env:RUNNER_TEMP\windows-build.zip
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: ${{ runner.temp }}\windows-build.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r linux-x64
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r linux-build.zip output/*

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: linux-build.zip

  build-linux-self-contained:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output-self-contained -r linux-x64 --self-contained
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r linux-build-self-contained.zip output-self-contained/*

    - name: Upload Linux self-contained build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary-self-contained
        path: linux-build-self-contained.zip

  build-macos-self-contained:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output-self-contained -r osx-x64 --self-contained
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r macos-build-self-contained.zip output-self-contained/*

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-binary-self-contained
        path: macos-build-self-contained.zip


  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r osx-x64
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r macos-build.zip output/*

    - name: Upload macOS build artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-binary
        path: macos-build.zip

  attach-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-linux-self-contained, build-macos, build-macos-self-contained]
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-binary
        path: ./release/windows

    - name: Download Linux build artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-binary
        path: ./release/linux

    - name: Download Linux self-contained build artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-binary-self-contained
        path: ./release/linux-self-contained

    - name: Download macOS build artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-binary
        path: ./release/macos

    - name: Download macOS self-contained build artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-binary-self-contained
        path: ./release/macos-self-contained

    - name: Get the latest release
      id: get_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: latestRelease } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return latestRelease;

    - name: Publish Windows build
      run: gh release upload "${{ github.ref_name }}" "./release/windows/windows-build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Linux build
      run: gh release upload "${{ github.ref_name }}" "./release/linux/linux-build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Linux self-contained build
      run: gh release upload "${{ github.ref_name }}" "./release/linux-self-contained/linux-build-self-contained.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish macOS build
      run: gh release upload "${{ github.ref_name }}" "./release/macos/macos-build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish macOS self-contained build
      run: gh release upload "${{ github.ref_name }}" "./release/macos-self-contained/macos-build-self-contained.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
