name: Build and Attach Release

on:
  push:
    branches:
      - actions

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r win-x64
      env:
        Configuration: Release

    - name: Compress build output
      run: |
        powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\output\* -DestinationPath $env:RUNNER_TEMP\windows-build.zip
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: ${{ runner.temp }}\windows-build.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r linux-x64
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r linux-build.zip output/*

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: linux-build.zip

  build-linux-self-contained:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --no-restore -c Release -o output -r linux-x64 --self-contained
      env:
        Configuration: Release

    - name: Compress build output
      run: zip -r linux-build-self-contained.zip output/*

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary-self-contained
        path: linux-build-self-contained.zip
