name: Build and Attach Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore -c Release -o output
      env:
        Configuration: Release
    - name: Archive binary
      run: zip -r windows-build.zip output/*
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: windows-build.zip

  attach-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-binary
        path: ./release/windows

    - name: Publish Windows build
      run: gh release upload "${{ github.ref_name }}" "./release/windows/windows-build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
