name: Build and Attach Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore -c Release -o output
      env:
        Configuration: Release

    - name: Compress build output
      run: |
        powershell Compress-Archive -Path $env:GITHUB_WORKSPACE\output\* -DestinationPath $env:RUNNER_TEMP\windows-build.zip
      env:
        RUNNER_TEMP: ${{ runner.temp }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: ${{ runner.temp }}\windows-build.zip

  attach-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-binary
        path: ./release/windows

    - name: Get the latest release
      id: get_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: latestRelease } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          return latestRelease;

    - name: Publish Windows build
      run: gh release upload "${{ github.ref_name }}" "./release/windows/windows-build.zip" --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
